Future getCategoryListPageJsonData() async {
  var result = {
    "status": "SUCCESS",
    "code": "200",
    "message": "Listed Successfully",
    "list": [
      {
        "id": 1,
        "title": "Fruit",
        "item": "43 items",
        "image": 'assets/images/c_fruits.png',
        "status": 1,
        "active": 1,
        "created_by": 101,
        "created_date": DateTime.now().toIso8601String(),
        "updated_by": 102,
        "updated_date": DateTime.now().toIso8601String(),
      },
      {
        "id": 2,
        "title": "Vegetables",
        "item": "43 items",
        "image": 'assets/images/c_vegetables.png',
        "status": 1,
        "active": 1,
        "created_by": 101,
        "created_date": DateTime.now().toIso8601String(),
        "updated_by": 102,
        "updated_date": DateTime.now().toIso8601String(),
      },
      {
        "id": 3,
        "title": "Bakery",
        "item": "43 items",
        "image": 'assets/images/c_Bakery.png',
        "status": 1,
        "active": 1,
        "created_by": 101,
        "created_date": DateTime.now().toIso8601String(),
        "updated_by": 102,
        "updated_date": DateTime.now().toIso8601String(),
      },
      {
        "id": 4,
        "title": "Dairy",
        "item": "43 items",
        "image": 'assets/images/c_Dairy.png',
        "status": 1,
        "active": 1,
        "created_by": 101,
        "created_date": DateTime.now().toIso8601String(),
        "updated_by": 102,
        "updated_date": DateTime.now().toIso8601String(),
      },
      {
        "id": 5,
        "title": "Mushroom",
        "item": "43 items",
        "image": 'assets/images/c_Mushroom.png',
        "status": 1,
        "active": 1,
        "created_by": 101,
        "created_date": DateTime.now().toIso8601String(),
        "updated_by": 102,
        "updated_date": DateTime.now().toIso8601String(),
      },
      {
        "id": 6,
        "title": "Fish",
        "item": "43 items",
        "image": 'assets/images/c_Fish.png',
        "status": 1,
        "active": 1,
        "created_by": 101,
        "created_date": DateTime.now().toIso8601String(),
        "updated_by": 102,
        "updated_date": DateTime.now().toIso8601String(),
      },
    ]
  };

  return result;
}
